name: Test Code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Initialize go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1
      - name: Test Code
        run: go test -v ./...
      - name: Build Binary
        run: go build -v ./...
